// ============================================================
// VNC PLATFORM — FRAUD ALERT SCREEN
// File: lib/screens/admin/fraud_alert_screen.dart
// FINAL MASTER HARD-LOCK v6.7.0.4
// ============================================================

import 'package:flutter/material.dart';

import '../../widgets/app_scaffold.dart';
import '../../widgets/empty_state_widget.dart';
import '../../services/admin_service.dart';

/// FraudAlertScreen
/// ----------------
/// Displays fraud alerts generated by AI / risk engine.
/// IMPORTANT:
/// - Frontend does NOT take action on alerts
/// - Frontend does NOT freeze accounts
/// - Backend enforces incident handling & audit
class FraudAlertScreen extends StatefulWidget {
  const FraudAlertScreen({super.key});

  @override
  State<FraudAlertScreen> createState() =>
      _FraudAlertScreenState();
}

class _FraudAlertScreenState
    extends State<FraudAlertScreen> {
  bool _loading = true;
  List<dynamic> _alerts = [];

  late final AdminService _adminService;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _adminService = AdminService.of(context);
    _load();
  }

  Future<void> _load() async {
    try {
      final items =
          await _adminService.getFraudAlerts();
      setState(() {
        _alerts = items;
      });
    } catch (_) {
      // silent fail
    } finally {
      setState(() {
        _loading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      title: 'Fraud Alerts',
      body: _loading
          ? const Center(
              child: CircularProgressIndicator(),
            )
          : _alerts.isEmpty
              ? const EmptyStateWidget(
                  title: 'No Alerts',
                  message:
                      'No fraud alerts at this time.',
                )
              : ListView.separated(
                  itemCount: _alerts.length,
                  separatorBuilder: (_, __) =>
                      const Divider(height: 1),
                  itemBuilder: (context, index) {
                    final a =
                        _alerts[index] as Map<String, dynamic>;
                    return ListTile(
                      leading: const Icon(
                        Icons.warning_amber_rounded,
                        color: Colors.redAccent,
                      ),
                      title: Text(
                        a['title']?.toString() ??
                            'Fraud Alert',
                      ),
                      subtitle: Text(
                        a['description']?.toString() ??
                            '',
                      ),
                      trailing: Column(
                        mainAxisAlignment:
                            MainAxisAlignment.center,
                        crossAxisAlignment:
                            CrossAxisAlignment.end,
                        children: [
                          Text(
                            a['severity']?.toString() ??
                                '',
                            style: const TextStyle(
                              fontWeight: FontWeight.bold,
                              color: Colors.red,
                            ),
                          ),
                          Text(
                            a['createdAt']?.toString() ??
                                '',
                            style: const TextStyle(
                              fontSize: 11,
                              color: Colors.grey,
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                ),
    );
  }
}
